version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  test:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Test
          command: poetry run pytest

workflows:
  main:
    jobs:
      - test
